"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest

scitex_dev = pytest.importorskip("scitex_dev")

if shutil.which("scitex-dev") is None:
    pytest.skip(
        "scitex-dev not installed — add `scitex-dev[cli-audit]` "
        "to [project.optional-dependencies.dev]",
        allow_module_level=True,
    )

from scitex_dev.testing import audit_all_for_package


def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    # audit_all_for_package returns None and raises/asserts non-zero exit
    # internally — asserting the None return keeps this gate a real
    # behavioural test (PS-206b) rather than an import smoke.
    assert audit_all_for_package("scitex-genai") is None
