"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


@pytest.fixture
def audit_all_for_package_callable():
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    return audit_all_for_package


def test_audit_all_for_package_returns_without_raising(
    audit_all_for_package_callable,
):
    # Arrange
    package_name = "scitex-genai"

    # Act
    # audit_all_for_package raises pytest.fail on any violation. Reaching the
    # next line at all means the audit corpus is clean for this package.
    audit_all_for_package_callable(package_name)
    completed = True

    # Assert
    assert completed is True
